# Generated by Django 5.1.5 on 2025-01-14 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Political_Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('foundation_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Deputy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('born_on', models.DateTimeField()),
                ('name', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='political_parties.political_party')),
            ],
        ),
    ]
